INFO 2022-06-01 14:20:49,307 autoreload Watching for file changes with StatReloader
INFO 2022-06-01 14:20:55,781 basehttp "GET / HTTP/1.1" 200 5511
INFO 2022-06-01 14:21:02,233 views some message in api-overview
INFO 2022-06-01 14:21:02,243 basehttp "GET /api-overview HTTP/1.1" 200 7699
INFO 2022-06-01 14:25:59,675 autoreload Watching for file changes with StatReloader
INFO 2022-06-01 14:26:02,453 views Hello from api-overview. How is loggin going?
INFO 2022-06-01 14:26:02,484 basehttp "GET /api-overview HTTP/1.1" 200 7699
INFO 2022-06-01 14:38:15,467 autoreload Watching for file changes with StatReloader
ERROR 2022-06-01 14:38:45,538 log Internal Server Error: /events/
Traceback (most recent call last):
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/epic_event/crm/views.py", line 150, in list
    return Response(serializer.data)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 357, in fields
    fields[key] = value
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/utils/serializer_helpers.py", line 152, in __setitem__
    field.bind(field_name=key, parent=self.serializer)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/fields.py", line 378, in bind
    assert self.source != field_name, (
AssertionError: It is redundant to specify `source='contract_id'` on field 'ReadOnlyField' in serializer 'EventSerializer', because it is the same as the field name. Remove the `source` keyword argument.
ERROR 2022-06-01 14:38:45,543 basehttp "GET /events/ HTTP/1.1" 500 134980
ERROR 2022-06-01 14:41:30,987 log Internal Server Error: /events/
Traceback (most recent call last):
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/epic_event/crm/views.py", line 150, in list
    return Response(serializer.data)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 357, in fields
    fields[key] = value
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/utils/serializer_helpers.py", line 152, in __setitem__
    field.bind(field_name=key, parent=self.serializer)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/fields.py", line 378, in bind
    assert self.source != field_name, (
AssertionError: It is redundant to specify `source='contract_id'` on field 'ReadOnlyField' in serializer 'EventSerializer', because it is the same as the field name. Remove the `source` keyword argument.
ERROR 2022-06-01 14:41:30,989 basehttp "GET /events/ HTTP/1.1" 500 134980
ERROR 2022-06-01 14:42:15,902 log Internal Server Error: /events/
Traceback (most recent call last):
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/epic_event/crm/views.py", line 150, in list
    return Response(serializer.data)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 357, in fields
    fields[key] = value
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/utils/serializer_helpers.py", line 152, in __setitem__
    field.bind(field_name=key, parent=self.serializer)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/fields.py", line 378, in bind
    assert self.source != field_name, (
AssertionError: It is redundant to specify `source='contract_id'` on field 'ReadOnlyField' in serializer 'EventSerializer', because it is the same as the field name. Remove the `source` keyword argument.
ERROR 2022-06-01 14:42:15,905 basehttp "GET /events/ HTTP/1.1" 500 134980
INFO 2022-06-01 14:42:33,847 basehttp "GET /events/* HTTP/1.1" 301 0
ERROR 2022-06-01 14:42:33,984 log Internal Server Error: /events/*/
Traceback (most recent call last):
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1988, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: '*'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/epic_event/crm/views.py", line 155, in retrieve
    project = get_object_or_404(queryset, pk=pk)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/shortcuts.py", line 85, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/db/models/query.py", line 482, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/db/models/query.py", line 1071, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/db/models/query.py", line 1089, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/db/models/query.py", line 1096, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1502, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1532, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1448, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/db/models/sql/query.py", line 1273, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/db/models/lookups.py", line 27, in __init__
    self.rhs = self.get_prep_lookup()
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/db/models/lookups.py", line 85, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/db/models/fields/__init__.py", line 1990, in get_prep_value
    raise e.__class__(
ValueError: Field 'id' expected a number but got '*'.
ERROR 2022-06-01 14:42:33,991 basehttp "GET /events/*/ HTTP/1.1" 500 153693
ERROR 2022-06-01 14:42:36,996 log Internal Server Error: /events/
Traceback (most recent call last):
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/viewsets.py", line 125, in view
    return self.dispatch(request, *args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/epic_event/crm/views.py", line 150, in list
    return Response(serializer.data)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super().data
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 253, in data
    self._data = self.to_representation(self.instance)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 686, in to_representation
    return [
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 687, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 507, in to_representation
    for field in fields:
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 368, in _readable_fields
    for field in self.fields.values():
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/serializers.py", line 357, in fields
    fields[key] = value
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/utils/serializer_helpers.py", line 152, in __setitem__
    field.bind(field_name=key, parent=self.serializer)
  File "/mnt/c/Users/galatee/OpenClassroom/P12/.env/lib/python3.10/site-packages/rest_framework/fields.py", line 378, in bind
    assert self.source != field_name, (
AssertionError: It is redundant to specify `source='contract_id'` on field 'ReadOnlyField' in serializer 'EventSerializer', because it is the same as the field name. Remove the `source` keyword argument.
ERROR 2022-06-01 14:42:36,998 basehttp "GET /events/ HTTP/1.1" 500 136889
